# Generated by Django 2.1 on 2018-09-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0004_auto_20180907_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='photo',
        ),
    ]
