# Generated by Django 2.1 on 2018-09-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0005_auto_20180907_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='path',
        ),
    ]
