# Generated by Django 2.1 on 2018-09-07 13:31

from django.db import migrations, models
import photoalbum.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0006_auto_20180907_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(max_length=128, upload_to=photoalbum.models.user_directory, verbose_name='Zdjęcie'),
        ),
    ]
