# Generated by Django 2.1 on 2018-09-09 11:45

from django.db import migrations
import easy_thumbnails.fields
import photoalbum.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0009_auto_20180909_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=128, upload_to=photoalbum.models.user_directory, verbose_name='Zdjęcie'),
        ),
    ]
