# Generated by Django 2.1 on 2018-09-09 12:06

from django.db import migrations, models
import photoalbum.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0010_auto_20180909_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=photoalbum.models.user_directory, verbose_name='Zdjęcie'),
        ),
    ]
