# Generated by Django 2.1 on 2018-09-09 15:31

from django.db import migrations, models
import photoalbum.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0012_auto_20180909_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=photoalbum.models.user_directory, verbose_name='Zdjęcie'),
        ),
    ]
