# Generated by Django 2.1 on 2018-09-10 07:39

from django.db import migrations, models
import photoalbum.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0014_auto_20180910_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(height_field='250',
                                    upload_to=photoalbum.models.user_directory,
                                    verbose_name='Zdjęcie',
                                    width_field='250'),
        ),
    ]
