# Generated by Django 2.1 on 2018-10-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0017_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
