# Generated by Django 2.1 on 2018-10-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0019_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
