# Generated by Django 2.1 on 2018-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0025_auto_20181018_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500, verbose_name='Komentarz'),
        ),
    ]
