# Generated by Django 2.1 on 2018-10-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0027_auto_20181018_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='picture',
            new_name='photo',
        ),
    ]
